import type { Opportunity } from "./types.js";

export const MOCK_OPPORTUNITIES: readonly Opportunity[] = [
  {
    id: "morpho-usdc-base",
    protocolId: "morpho",
    protocolName: "Morpho",
    asset: "USDC",
    chain: "Base",
    apy: 0.071,
    isExperimental: false,
    protocolRiskLevel: "low",
    auditCount: 2,
    exposureCategory: "lending",
  },
  {
    id: "aave-usdc-base",
    protocolId: "aave",
    protocolName: "Aave",
    asset: "USDC",
    chain: "Base",
    apy: 0.052,
    isExperimental: false,
    protocolRiskLevel: "low",
    auditCount: 2,
    exposureCategory: "lending",
  },
  {
    id: "moonwell-usdc-base",
    protocolId: "moonwell",
    protocolName: "Moonwell",
    asset: "USDC",
    chain: "Base",
    apy: 0.048,
    isExperimental: false,
    protocolRiskLevel: "medium",
    auditCount: 2,
    exposureCategory: "lending",
  },
  {
    id: "aave-eurc-base",
    protocolId: "aave",
    protocolName: "Aave",
    asset: "EURC",
    chain: "Base",
    apy: 0.041,
    isExperimental: false,
    protocolRiskLevel: "low",
    auditCount: 2,
    exposureCategory: "lending",
  },
  {
    id: "moonwell-dai-base",
    protocolId: "moonwell",
    protocolName: "Moonwell",
    asset: "DAI",
    chain: "Base",
    apy: 0.039,
    isExperimental: false,
    protocolRiskLevel: "medium",
    auditCount: 2,
    exposureCategory: "lending",
  },
  {
    id: "experimental-usdc-base",
    protocolId: "experimental-lend",
    protocolName: "Experimental Lend",
    asset: "USDC",
    chain: "Base",
    apy: 0.112,
    isExperimental: true,
    protocolRiskLevel: "high",
    auditCount: 1,
    exposureCategory: "lending",
  },
  {
    id: "aave-prime-usdc-base",
    protocolId: "aave-prime",
    protocolName: "Aave Prime",
    asset: "USDC",
    chain: "Base",
    apy: 0.037,
    isExperimental: false,
    protocolRiskLevel: "low",
    auditCount: 3,
    exposureCategory: "lending",
  },
  {
    id: "aerodrome-usdc-eurc-base",
    protocolId: "aerodrome",
    protocolName: "Aerodrome",
    asset: "USDC",
    chain: "Base",
    apy: 0.105,
    isExperimental: false,
    protocolRiskLevel: "medium",
    auditCount: 2,
    exposureCategory: "yieldEnhancement",
  },
  {
    id: "spectra-yield-usdc-base",
    protocolId: "spectra-yield",
    protocolName: "Spectra Yield",
    asset: "USDC",
    chain: "Base",
    apy: 0.11,
    isExperimental: true,
    protocolRiskLevel: "medium",
    auditCount: 1,
    exposureCategory: "lending",
  },
] as const;
